version: "3.4"

services:
  api:
    image: ccs/sih-24
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8789:8789"
    volumes:
      - ./logs/:/app/logs/
    restart: always
